project:
  type: website
  output-dir: docs

website:
  title: "Samira Ardani"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - interest.qmd
      - teachinhg.qmd
      - research.qmd
      
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

